---
# nginx
- name: Stop apache2
  service: apache2
    state: stopped
- name: Install nginx
  apt: 
    pkg:
      name: nginx 
- name: Start nginx
  service: name=nginx state=started
- name: Create nginx config
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx
- name: Remove apache2
  apt: 
    pkg:
      name: apache2
    state: absent 
# tasks file for gw2019.nginx
