---
- name: show return value of apt module
  hosts: web
  gather_facts: False
  become: True
  tasks:
    - name: install nginx
      apt: update_cache=yes
      register: result
    - debug: var=result
