---
# - name: Add the ondrej PHP PPA
# PHP
- name: Add the ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php'
- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: Install PHP
  apt:
    pkg:
      - php
      - php-fpm
      - php-mysql
      - php-xml
# tasks file for gw2019.php
